version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: back
    ports:
      - 5192:5192
    networks:
      - diploma_net
    environment:
      - DB_SERVER=db
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: always
    image: postgres
    # volumes:
    #   - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dip
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    ports:
      - 5431:5432
    networks:
      - diploma_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 3

networks:
  diploma_net:
    name: diploma_net
